-- =========================================
-- SCHEMA
-- =========================================
CREATE SCHEMA IF NOT EXISTS pessoa;
SET search_path TO pessoa;

-- =========================================
-- EXTENSÕES
-- =========================================
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================
-- ENUMS
-- =========================================
CREATE TYPE tipo_pessoa_enum AS ENUM ('fisica','juridica','grupo');
CREATE TYPE status_enum AS ENUM ('ativo','inativo','suspenso');

CREATE TYPE sexo_enum AS ENUM ('masculino','feminino','outro','nao_informado');

CREATE TYPE estado_civil_enum AS ENUM (
    'solteiro','casado','divorciado','viuvo',
    'uniao_estavel','separado','nao_informado'
);

CREATE TYPE tipo_local_enum AS ENUM (
    'pais','estado','municipio','bairro',
    'logradouro','regiao','area_geografica',
    'estabelecimento','local_generico'
);

CREATE TYPE tipo_contato_enum AS ENUM (
    'telefone','email','endereco','pessoa_relacionada'
);

CREATE TYPE classificacao_contato_enum AS ENUM (
    'residencial','comercial','outro'
);

CREATE TYPE papel_grupo_enum AS ENUM (
    'gestor','membro','associado','interessado'
);

-- =========================================
-- LOCAL
-- =========================================
CREATE TABLE local (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipo tipo_local_enum NOT NULL,
    id_local_pai BIGINT,
    FOREIGN KEY (id_local_pai) REFERENCES local(id)
);

CREATE INDEX idx_local_pai ON local(id_local_pai);

-- =========================================
-- PESSOA
-- =========================================
CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipo tipo_pessoa_enum NOT NULL,
    status status_enum NOT NULL DEFAULT 'ativo',
    observacao TEXT,

    criado_por BIGINT NOT NULL,
    criacao_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_por BIGINT NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_pessoa_tipo ON pessoa(tipo);
CREATE INDEX idx_pessoa_status ON pessoa(status);

-- =========================================
-- PROFISSAO
-- =========================================
CREATE TABLE profissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

-- =========================================
-- PESSOA FISICA
-- =========================================
CREATE TABLE pessoa_fisica (
    id BIGINT PRIMARY KEY,
    cpf VARCHAR(11),
    rg VARCHAR(20),

    id_pessoa_mae BIGINT,
    id_pessoa_pai BIGINT,
    nome_mae VARCHAR(255),
    nome_pai VARCHAR(255),

    data_nascimento DATE,
    local_nascimento_nome VARCHAR(255),
    id_local_nascimento BIGINT,

    data_falecimento DATE,
    local_falecimento_nome VARCHAR(255),
    id_local_falecimento BIGINT,

    sexo sexo_enum,
    estado_civil estado_civil_enum,
    nacionalidade VARCHAR(100),

    id_profissao BIGINT,
    profissao_nome VARCHAR(255),

    FOREIGN KEY (id) REFERENCES pessoa(id) ON DELETE CASCADE,
    FOREIGN KEY (id_pessoa_mae) REFERENCES pessoa(id),
    FOREIGN KEY (id_pessoa_pai) REFERENCES pessoa(id),
    FOREIGN KEY (id_local_nascimento) REFERENCES local(id),
    FOREIGN KEY (id_local_falecimento) REFERENCES local(id),
    FOREIGN KEY (id_profissao) REFERENCES profissao(id)
);

CREATE UNIQUE INDEX uq_pf_cpf ON pessoa_fisica(cpf) WHERE cpf IS NOT NULL;

-- =========================================
-- PESSOA JURIDICA
-- =========================================
CREATE TABLE pessoa_juridica (
    id BIGINT PRIMARY KEY,

    cnpj VARCHAR(14),
    razao_social VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255),

    data_abertura DATE,
    local_abertura_nome VARCHAR(255),
    id_local_abertura BIGINT,

    data_fechamento DATE,
    local_fechamento_nome VARCHAR(255),
    id_local_fechamento BIGINT,

    natureza_juridica VARCHAR(100),
    regime_tributario VARCHAR(50),
    porte VARCHAR(20),
    capital_social NUMERIC(15,2),

    id_empresa_controladora BIGINT,

    FOREIGN KEY (id) REFERENCES pessoa(id) ON DELETE CASCADE,
    FOREIGN KEY (id_empresa_controladora) REFERENCES pessoa_juridica(id),
    FOREIGN KEY (id_local_abertura) REFERENCES local(id),
    FOREIGN KEY (id_local_fechamento) REFERENCES local(id)
);

CREATE UNIQUE INDEX uq_pj_cnpj ON pessoa_juridica(cnpj) WHERE cnpj IS NOT NULL;

-- =========================================
-- PESSOA GRUPO
-- =========================================
CREATE TABLE pessoa_grupo (
    id BIGINT PRIMARY KEY,
    descricao VARCHAR(255),
    data_criacao_grupo DATE,
    data_encerramento_grupo DATE,
    FOREIGN KEY (id) REFERENCES pessoa(id) ON DELETE CASCADE
);

-- =========================================
-- TRIGGERS INATIVACAO
-- =========================================
CREATE OR REPLACE FUNCTION trg_inativar_pf()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.data_falecimento IS NOT NULL
       OR NEW.local_falecimento_nome IS NOT NULL
       OR NEW.id_local_falecimento IS NOT NULL THEN
        UPDATE pessoa SET status = 'inativo' WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pf_inativo
AFTER INSERT OR UPDATE ON pessoa_fisica
FOR EACH ROW EXECUTE FUNCTION trg_inativar_pf();

CREATE OR REPLACE FUNCTION trg_inativar_pj()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.data_fechamento IS NOT NULL
       OR NEW.local_fechamento_nome IS NOT NULL
       OR NEW.id_local_fechamento IS NOT NULL THEN
        UPDATE pessoa SET status = 'inativo' WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pj_inativo
AFTER INSERT OR UPDATE ON pessoa_juridica
FOR EACH ROW EXECUTE FUNCTION trg_inativar_pj();

CREATE OR REPLACE FUNCTION trg_inativar_grupo()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.data_encerramento_grupo IS NOT NULL THEN
        UPDATE pessoa SET status = 'inativo' WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_grupo_inativo
AFTER INSERT OR UPDATE ON pessoa_grupo
FOR EACH ROW EXECUTE FUNCTION trg_inativar_grupo();

-- =========================================
-- VALIDACAO PAI/MAE
-- =========================================
CREATE OR REPLACE FUNCTION trg_validar_pais()
RETURNS TRIGGER AS $$
DECLARE sexo_mae sexo_enum;
DECLARE sexo_pai sexo_enum;
BEGIN
    IF NEW.id_pessoa_mae IS NOT NULL THEN
        SELECT sexo INTO sexo_mae FROM pessoa_fisica WHERE id = NEW.id_pessoa_mae;
        IF sexo_mae <> 'feminino' THEN
            RAISE EXCEPTION 'Mãe inválida';
        END IF;
    END IF;

    IF NEW.id_pessoa_pai IS NOT NULL THEN
        SELECT sexo INTO sexo_pai FROM pessoa_fisica WHERE id = NEW.id_pessoa_pai;
        IF sexo_pai <> 'masculino' THEN
            RAISE EXCEPTION 'Pai inválido';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_pais
BEFORE INSERT OR UPDATE ON pessoa_fisica
FOR EACH ROW EXECUTE FUNCTION trg_validar_pais();

-- =========================================
-- CONTATO
-- =========================================
CREATE TABLE contato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo tipo_contato_enum NOT NULL
);

CREATE TABLE pessoa_contato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pessoa BIGINT NOT NULL,
    id_contato BIGINT NOT NULL,
    tipo tipo_contato_enum NOT NULL,
    classificacao classificacao_contato_enum,
    prioridade INTEGER,

    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id) ON DELETE CASCADE,
    FOREIGN KEY (id_contato) REFERENCES contato(id) ON DELETE CASCADE
);

CREATE INDEX idx_pc_lookup ON pessoa_contato(id_pessoa, tipo, prioridade);

-- TELEFONE
CREATE TABLE contato_telefone (
    id BIGINT PRIMARY KEY,
    numero VARCHAR(20) NOT NULL,
    FOREIGN KEY (id) REFERENCES contato(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_tel_numero ON contato_telefone(numero);

-- EMAIL
CREATE TABLE contato_email (
    id BIGINT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    FOREIGN KEY (id) REFERENCES contato(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_email ON contato_email(email);

-- ENDERECO
CREATE TABLE contato_endereco (
    id BIGINT PRIMARY KEY,
    cep VARCHAR(10),
    logradouro VARCHAR(255),
    numero VARCHAR(20),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    referencia TEXT,
    id_local BIGINT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    geometria GEOMETRY,
    hash_endereco BYTEA,

    FOREIGN KEY (id) REFERENCES contato(id) ON DELETE CASCADE,
    FOREIGN KEY (id_local) REFERENCES local(id)
);

CREATE OR REPLACE FUNCTION normalizar_texto(t TEXT)
RETURNS TEXT AS $$ BEGIN RETURN lower(trim(coalesce(t,''))); END; $$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION trg_hash_endereco()
RETURNS TRIGGER AS $$
BEGIN
    NEW.hash_endereco :=
        digest(
            normalizar_texto(NEW.cep) ||
            normalizar_texto(NEW.logradouro) ||
            normalizar_texto(NEW.numero) ||
            normalizar_texto(NEW.complemento) ||
            normalizar_texto(NEW.bairro) ||
            coalesce(NEW.id_local::text,''),
            'sha256'
        );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_hash_endereco
BEFORE INSERT OR UPDATE ON contato_endereco
FOR EACH ROW EXECUTE FUNCTION trg_hash_endereco();

CREATE UNIQUE INDEX uq_endereco_hash ON contato_endereco(hash_endereco);

-- =========================================
-- GRUPOS
-- =========================================
CREATE TABLE pessoa_grupo_membros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupo BIGINT NOT NULL,
    id_pessoa BIGINT NOT NULL,
    papel papel_grupo_enum NOT NULL,
    descricao_funcao VARCHAR(255),
    data_entrada TIMESTAMPTZ DEFAULT now(),
    data_saida TIMESTAMPTZ,

    FOREIGN KEY (id_grupo) REFERENCES pessoa_grupo(id),
    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id)
);

CREATE UNIQUE INDEX uq_pg_membro_ativo
ON pessoa_grupo_membros(id_grupo, id_pessoa)
WHERE data_saida IS NULL;

CREATE TABLE pessoa_grupo_hierarquia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupo_pai BIGINT NOT NULL,
    id_grupo_filho BIGINT NOT NULL,
    nome_pai_para_filho VARCHAR(255),
    nome_filho_para_pai VARCHAR(255),

    FOREIGN KEY (id_grupo_pai) REFERENCES pessoa_grupo(id),
    FOREIGN KEY (id_grupo_filho) REFERENCES pessoa_grupo(id)
);

-- =========================================
-- GRAFO DE RELACOES
-- =========================================
CREATE TABLE relacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(100) NOT NULL,
    descricao TEXT
);

CREATE TABLE funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT
);

CREATE TABLE pessoa_relacionamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_relacao BIGINT NOT NULL,
    id_pessoa BIGINT NOT NULL,
    id_funcao BIGINT,
    descricao_funcao VARCHAR(255),
    data_inicio TIMESTAMPTZ DEFAULT now(),
    data_fim TIMESTAMPTZ,

    FOREIGN KEY (id_relacao) REFERENCES relacao(id),
    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id),
    FOREIGN KEY (id_funcao) REFERENCES funcao(id)
);

CREATE UNIQUE INDEX uq_relacao_pessoa_funcao_ativa
ON pessoa_relacionamento(id_relacao,id_pessoa,id_funcao)
WHERE data_fim IS NULL;

-- =========================================
-- VIEWS (HIERARQUIA)
-- =========================================
CREATE VIEW vw_grupo_hierarquia_desc AS
WITH RECURSIVE arvore AS (
    SELECT id_grupo_pai,id_grupo_filho,1 nivel
    FROM pessoa_grupo_hierarquia
    UNION ALL
    SELECT a.id_grupo_pai,h.id_grupo_filho,a.nivel+1
    FROM pessoa_grupo_hierarquia h
    JOIN arvore a ON a.id_grupo_filho = h.id_grupo_pai
)
SELECT * FROM arvore;

CREATE VIEW vw_grupo_membros_ativos AS
SELECT *
FROM pessoa_grupo_membros
WHERE data_saida IS NULL;
