-- =========================================
-- SCHEMA
-- =========================================
CREATE SCHEMA IF NOT EXISTS pessoa;
SET search_path TO pessoa;

-- =========================================
-- ENUMS
-- =========================================
CREATE TYPE tipo_pessoa_enum AS ENUM ('fisica','juridica','grupo');
CREATE TYPE status_enum AS ENUM ('ativo','inativo','suspenso');

CREATE TYPE sexo_enum AS ENUM ('masculino','feminino','outro','nao_informado');

CREATE TYPE estado_civil_enum AS ENUM (
    'solteiro','casado','divorciado','viuvo',
    'uniao_estavel','separado','nao_informado'
);

CREATE TYPE nacionalidade_enum AS ENUM (
    'brasileira','estrangeira','nacionalizado','nao_informado'
);

CREATE TYPE tipo_local_enum AS ENUM (
    'pais','estado','municipio','bairro',
    'logradouro','regiao','area_geografica',
    'estabelecimento','local_generico'
);

CREATE TYPE tipo_contato_enum AS ENUM (
    'telefone','email','endereco','pessoa_relacionada'
);

CREATE TYPE classificacao_contato_enum AS ENUM (
    'residencial','comercial','outro'
);

CREATE TYPE papel_grupo_enum AS ENUM (
    'gestor','membro','associado','interessado'
);

-- =========================================
-- LOCAL
-- =========================================
CREATE TABLE local (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    sigla TEXT,
    tipo tipo_local_enum NOT NULL,

    id_local_pai BIGINT,

    centroide public.geometry(Point, 4326),
    area public.geometry(MultiPolygon, 4326),

    FOREIGN KEY (id_local_pai) REFERENCES local(id)
);

CREATE INDEX idx_local_pai ON local(id_local_pai);
CREATE INDEX idx_local_area ON local USING GIST (area);

-- =========================================
-- PESSOA
-- =========================================
CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nome TEXT NOT NULL,
    tipo tipo_pessoa_enum NOT NULL,
    status status_enum NOT NULL DEFAULT 'ativo',

    observacao TEXT,

    data_inicio DATE,
    data_termino DATE,

    criado_por BIGINT NOT NULL,
    criacao_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_por BIGINT NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_pessoa_tipo ON pessoa(tipo);
CREATE INDEX idx_pessoa_status ON pessoa(status);

-- =========================
-- TRIGGER AUDITORIA
-- =========================
CREATE OR REPLACE FUNCTION trg_set_auditoria()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.atualizado_por := NEW.criado_por;
        NEW.atualizado_em := NEW.criacao_em;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_auditoria_pessoa
BEFORE INSERT ON pessoa
FOR EACH ROW
EXECUTE FUNCTION trg_set_auditoria();


-- =========================================
-- PROFISSAO
-- =========================================
CREATE TABLE profissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL
);

-- =========================================
-- PESSOA FISICA
-- =========================================
CREATE TABLE pessoa_fisica (
    id BIGINT PRIMARY KEY,

    cpf VARCHAR(11),
    rg TEXT,

    apelido TEXT,

    id_pessoa_mae BIGINT,
    id_pessoa_pai BIGINT,

    nome_mae TEXT,
    nome_pai TEXT,

    local_nascimento_nome TEXT,
    id_local_nascimento BIGINT,

    local_falecimento_nome TEXT,
    id_local_falecimento BIGINT,

    sexo sexo_enum,
    estado_civil estado_civil_enum,
    nacionalidade nacionalidade_enum,

    id_profissao BIGINT,
    profissao_nome TEXT,

    FOREIGN KEY (id) REFERENCES pessoa(id) ON DELETE CASCADE,
    FOREIGN KEY (id_pessoa_mae) REFERENCES pessoa(id),
    FOREIGN KEY (id_pessoa_pai) REFERENCES pessoa(id),
    FOREIGN KEY (id_local_nascimento) REFERENCES local(id),
    FOREIGN KEY (id_local_falecimento) REFERENCES local(id),
    FOREIGN KEY (id_profissao) REFERENCES profissao(id)
);

CREATE UNIQUE INDEX uq_pf_cpf ON pessoa_fisica(cpf) WHERE cpf IS NOT NULL;

-- =========================================
-- PESSOA JURIDICA
-- =========================================
CREATE TABLE pessoa_juridica (
    id BIGINT PRIMARY KEY,

    cnpj VARCHAR(14),

    razao_social TEXT NOT NULL,
    sigla TEXT,

    local_sede_nome TEXT,
    id_local_sede BIGINT,

    natureza_juridica TEXT,
    regime_tributario TEXT,
    porte TEXT,

    capital_social NUMERIC(15,2),

    id_empresa_controladora BIGINT,

    FOREIGN KEY (id) REFERENCES pessoa(id) ON DELETE CASCADE,
    FOREIGN KEY (id_local_sede) REFERENCES local(id),
    FOREIGN KEY (id_empresa_controladora) REFERENCES pessoa_juridica(id)
);

CREATE UNIQUE INDEX uq_pj_cnpj ON pessoa_juridica(cnpj) WHERE cnpj IS NOT NULL;

-- =========================================
-- PESSOA GRUPO
-- =========================================
CREATE TABLE pessoa_grupo (
    id BIGINT PRIMARY KEY,
    descricao TEXT,
    nome_resumido_sigla TEXT,
    FOREIGN KEY (id) REFERENCES pessoa(id) ON DELETE CASCADE
);

-- =========================================
-- TRIGGERS DE INATIVACAO
-- =========================================
CREATE OR REPLACE FUNCTION trg_inativar_pf()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.local_falecimento_nome IS NOT NULL
       OR NEW.id_local_falecimento IS NOT NULL THEN
        UPDATE pessoa SET status = 'inativo' WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pf_inativo
AFTER INSERT OR UPDATE ON pessoa_fisica
FOR EACH ROW EXECUTE FUNCTION trg_inativar_pf();

CREATE OR REPLACE FUNCTION trg_inativar_pj()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.local_sede_nome IS NULL AND NEW.id_local_sede IS NULL THEN
        RETURN NEW;
    END IF;
    IF EXISTS (
        SELECT 1 FROM pessoa p WHERE p.id = NEW.id AND p.data_termino IS NOT NULL
    ) THEN
        UPDATE pessoa SET status = 'inativo' WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pj_inativo
AFTER INSERT OR UPDATE ON pessoa_juridica
FOR EACH ROW EXECUTE FUNCTION trg_inativar_pj();

CREATE OR REPLACE FUNCTION trg_inativar_grupo()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.data_termino IS NOT NULL THEN
        UPDATE pessoa SET status = 'inativo' WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_grupo_inativo
AFTER INSERT OR UPDATE ON pessoa_grupo
FOR EACH ROW EXECUTE FUNCTION trg_inativar_grupo();

-- =========================================
-- VALIDACAO PAI/MAE
-- =========================================
CREATE OR REPLACE FUNCTION trg_validar_pais()
RETURNS TRIGGER AS $$
DECLARE sexo_mae sexo_enum;
DECLARE sexo_pai sexo_enum;
BEGIN
    IF NEW.id_pessoa_mae IS NOT NULL THEN
        SELECT sexo INTO sexo_mae FROM pessoa_fisica WHERE id = NEW.id_pessoa_mae;
        IF sexo_mae <> 'feminino' THEN
            RAISE EXCEPTION 'Mãe inválida';
        END IF;
    END IF;

    IF NEW.id_pessoa_pai IS NOT NULL THEN
        SELECT sexo INTO sexo_pai FROM pessoa_fisica WHERE id = NEW.id_pessoa_pai;
        IF sexo_pai <> 'masculino' THEN
            RAISE EXCEPTION 'Pai inválido';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_pais
BEFORE INSERT OR UPDATE ON pessoa_fisica
FOR EACH ROW EXECUTE FUNCTION trg_validar_pais();

-- =========================================
-- CONTATO
-- =========================================
CREATE TABLE contato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo tipo_contato_enum NOT NULL
);

CREATE TABLE pessoa_contato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_pessoa BIGINT NOT NULL,
    id_contato BIGINT NOT NULL,

    classificacao classificacao_contato_enum,
    prioridade INTEGER,

    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id),
    FOREIGN KEY (id_contato) REFERENCES contato(id)
);

CREATE INDEX idx_pc_lookup ON pessoa_contato(id_pessoa, prioridade);

-- =========================================
-- TELEFONE
-- =========================================
CREATE TABLE contato_telefone (
    id BIGINT PRIMARY KEY,

    numero TEXT NOT NULL,
    numero_normalizado TEXT NOT NULL,

    FOREIGN KEY (id) REFERENCES contato(id)
);

CREATE UNIQUE INDEX uq_tel_norm ON contato_telefone(numero_normalizado);

-- =========================================
-- EMAIL
-- =========================================
CREATE TABLE contato_email (
    id BIGINT PRIMARY KEY,

    email TEXT NOT NULL,
    email_normalizado TEXT NOT NULL,

    FOREIGN KEY (id) REFERENCES contato(id)
);

CREATE UNIQUE INDEX uq_email_norm ON contato_email(email_normalizado);

-- =========================================
-- ENDERECO
-- =========================================
CREATE TABLE contato_endereco (
    id BIGINT PRIMARY KEY,

    cep VARCHAR(10),
    logradouro TEXT,
    numero TEXT,
    complemento TEXT,
    bairro TEXT,
    referencia TEXT,

    id_local BIGINT,

    localizacao public.geometry(Point, 4326),
    area public.geometry(MultiPolygon, 4326),

    hash_endereco BYTEA,

    FOREIGN KEY (id) REFERENCES contato(id),
    FOREIGN KEY (id_local) REFERENCES local(id)
);

-- HASH ENDERECO
CREATE OR REPLACE FUNCTION normalizar_texto(t TEXT)
RETURNS TEXT AS $$
BEGIN
    RETURN lower(trim(coalesce(t,'')));
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION trg_hash_endereco()
RETURNS TRIGGER AS $$
BEGIN
    NEW.hash_endereco :=
        digest(
            normalizar_texto(NEW.cep) ||
            normalizar_texto(NEW.logradouro) ||
            normalizar_texto(NEW.numero) ||
            normalizar_texto(NEW.complemento) ||
            normalizar_texto(NEW.bairro) ||
            coalesce(NEW.id_local::text,''),
            'sha256'
        );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_hash_endereco
BEFORE INSERT OR UPDATE ON contato_endereco
FOR EACH ROW EXECUTE FUNCTION trg_hash_endereco();

CREATE UNIQUE INDEX uq_endereco_hash ON contato_endereco(hash_endereco);

-- =========================================
-- CONTATO PESSOA RELACIONADA
-- =========================================
CREATE TABLE contato_pessoa_relacionada (
    id BIGINT PRIMARY KEY,

    id_pessoa_relacionada BIGINT,
    nome TEXT,
    descricao TEXT,

    FOREIGN KEY (id) REFERENCES contato(id),
    FOREIGN KEY (id_pessoa_relacionada) REFERENCES pessoa(id)
);

-- =========================================
-- GRUPOS
-- =========================================
CREATE TABLE pessoa_grupo_membros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupo BIGINT NOT NULL,
    id_pessoa BIGINT NOT NULL,
    papel papel_grupo_enum NOT NULL,
    descricao_funcao VARCHAR(255),
    data_entrada TIMESTAMPTZ DEFAULT now(),
    data_saida TIMESTAMPTZ,

    FOREIGN KEY (id_grupo) REFERENCES pessoa_grupo(id),
    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id)
);

CREATE UNIQUE INDEX uq_pg_membro_ativo
ON pessoa_grupo_membros(id_grupo, id_pessoa)
WHERE data_saida IS NULL;

CREATE TABLE pessoa_grupo_hierarquia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupo_pai BIGINT NOT NULL,
    id_grupo_filho BIGINT NOT NULL,
    nome_pai_para_filho VARCHAR(255),
    nome_filho_para_pai VARCHAR(255),

    FOREIGN KEY (id_grupo_pai) REFERENCES pessoa_grupo(id),
    FOREIGN KEY (id_grupo_filho) REFERENCES pessoa_grupo(id)
);

-- =========================================
-- RELACIONAMENTOS (GRAFO)
-- =========================================
CREATE TABLE relacao_tipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL
);

CREATE UNIQUE INDEX uq_relacao_tipo_nome ON relacao_tipo(nome);

CREATE TABLE relacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_relacao_tipo BIGINT NOT NULL,
    FOREIGN KEY (id_relacao_tipo) REFERENCES relacao_tipo(id)
);

CREATE TABLE relacao_tipo_funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_relacao_tipo BIGINT NOT NULL,
    nome TEXT NOT NULL,
    sexo sexo_enum,

    FOREIGN KEY (id_relacao_tipo) REFERENCES relacao_tipo(id)
);

CREATE UNIQUE INDEX uq_relacao_tipo_funcao
ON relacao_tipo_funcao(id_relacao_tipo, nome);

CREATE TABLE pessoa_relacionamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_relacao BIGINT NOT NULL,
    id_pessoa BIGINT NOT NULL,
    id_relacao_tipo_funcao BIGINT NOT NULL,

    data_inicio TIMESTAMPTZ DEFAULT now(),
    data_fim TIMESTAMPTZ,

    FOREIGN KEY (id_relacao) REFERENCES relacao(id),
    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id),
    FOREIGN KEY (id_relacao_tipo_funcao) REFERENCES relacao_tipo_funcao(id)
);

CREATE UNIQUE INDEX uq_relacao_pessoa_funcao_ativa
ON pessoa_relacionamento(id_relacao, id_pessoa, id_relacao_tipo_funcao)
WHERE data_fim IS NULL;

CREATE INDEX idx_pr_relacao ON pessoa_relacionamento(id_relacao);
CREATE INDEX idx_pr_pessoa ON pessoa_relacionamento(id_pessoa);
-- =========================================
-- VIEWS (HIERARQUIA)
-- =========================================
CREATE OR REPLACE VIEW pessoa.vw_grupo_hierarquia_desc AS
WITH RECURSIVE arvore AS (
    SELECT
        h.id_grupo_pai,
        h.id_grupo_filho,
        1 AS nivel,
        ARRAY[h.id_grupo_pai, h.id_grupo_filho] AS caminho
    FROM pessoa.pessoa_grupo_hierarquia h

    UNION ALL

    SELECT
        a.id_grupo_pai,
        h.id_grupo_filho,
        a.nivel + 1,
        a.caminho || h.id_grupo_filho
    FROM pessoa.pessoa_grupo_hierarquia h
    JOIN arvore a
        ON a.id_grupo_filho = h.id_grupo_pai
)
SELECT * FROM arvore;

CREATE OR REPLACE VIEW pessoa.vw_grupo_hierarquia_asc AS
WITH RECURSIVE arvore AS (
    SELECT
        h.id_grupo_pai,
        h.id_grupo_filho,
        1 AS nivel
    FROM pessoa.pessoa_grupo_hierarquia h

    UNION ALL

    SELECT
        h.id_grupo_pai,
        a.id_grupo_filho,
        a.nivel + 1
    FROM pessoa.pessoa_grupo_hierarquia h
    JOIN arvore a
        ON h.id_grupo_filho = a.id_grupo_pai
)
SELECT * FROM arvore;

CREATE VIEW vw_grupo_membros_ativos AS
SELECT *
FROM pessoa_grupo_membros
WHERE data_saida IS NULL;


CREATE OR REPLACE VIEW pessoa.vw_grupo_membros_hierarquia AS
WITH RECURSIVE arvore AS (
    SELECT
        g.id AS id_grupo_raiz,
        g.id AS id_grupo
    FROM pessoa.pessoa_grupo g

    UNION ALL

    SELECT
        a.id_grupo_raiz,
        h.id_grupo_filho
    FROM pessoa.pessoa_grupo_hierarquia h
    JOIN arvore a ON a.id_grupo = h.id_grupo_pai
)
SELECT
    a.id_grupo_raiz AS id_grupo,
    gm.id_pessoa,
    gm.papel,
    gm.descricao_funcao
FROM arvore a
JOIN pessoa.pessoa_grupo_membros gm
    ON gm.id_grupo = a.id_grupo
WHERE gm.data_saida IS NULL;

CREATE OR REPLACE VIEW pessoa.vw_grupo_hierarquia_nomeada AS
SELECT
    h.id_grupo_pai,
    p1.nome AS nome_grupo_pai,

    h.id_grupo_filho,
    p2.nome AS nome_grupo_filho,

    h.nome_pai_para_filho,
    h.nome_filho_para_pai
FROM pessoa.pessoa_grupo_hierarquia h
JOIN pessoa.pessoa p1 ON p1.id = h.id_grupo_pai
JOIN pessoa.pessoa p2 ON p2.id = h.id_grupo_filho;

CREATE OR REPLACE VIEW pessoa.vw_grupo_caminho AS
WITH RECURSIVE arvore AS (
    SELECT
        h.id_grupo_pai,
        h.id_grupo_filho,
        p1.nome::TEXT || ' > ' || p2.nome::TEXT AS caminho
    FROM pessoa.pessoa_grupo_hierarquia h
    JOIN pessoa.pessoa p1 ON p1.id = h.id_grupo_pai
    JOIN pessoa.pessoa p2 ON p2.id = h.id_grupo_filho

    UNION ALL

    SELECT
        a.id_grupo_pai,
        h.id_grupo_filho,
        a.caminho || ' > ' || p.nome
    FROM pessoa.pessoa_grupo_hierarquia h
    JOIN arvore a ON a.id_grupo_filho = h.id_grupo_pai
    JOIN pessoa.pessoa p ON p.id = h.id_grupo_filho
)
SELECT * FROM arvore;
