-- DROP SCHEMA seguranca;

CREATE SCHEMA IF NOT EXISTS seguranca;
SET search_path TO seguranca;


-- seguranca.consentimento definition

-- Drop table

-- DROP TABLE seguranca.consentimento;

CREATE TABLE seguranca.consentimento (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizacao_id uuid NOT NULL,
	usuario_id varchar(64) NOT NULL,
	tipo_consentimento varchar(64) NOT NULL,
	status varchar(32) DEFAULT 'ATIVO'::character varying NOT NULL,
	criado_por varchar(64) NOT NULL,
	criado_em timestamp NOT NULL,
	atualizado_por varchar(64) NULL,
	atualizado_em timestamp NULL
);


-- seguranca.dispositivo definition

-- Drop table

-- DROP TABLE seguranca.dispositivo;

CREATE TABLE seguranca.dispositivo (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	identificador_dispositivo varchar(128) NOT NULL,
	usuario_id varchar(64) NULL,
	nivel_confianca varchar(16) NOT NULL,
	plataforma varchar(32) NULL,
	criado_por varchar(64) NOT NULL,
	criado_em timestamp NOT NULL,
	atualizado_por varchar(64) NULL,
	atualizado_em timestamp NULL,
	CONSTRAINT dispositivo_identificador_dispositivo_key_1 UNIQUE (identificador_dispositivo)
);


-- seguranca.excecao_permissao_usuario definition

-- Drop table

-- DROP TABLE seguranca.excecao_permissao_usuario;

CREATE TABLE seguranca.excecao_permissao_usuario (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizacao_id uuid NOT NULL,
	usuario_id varchar(64) NOT NULL,
	recurso varchar(128) NOT NULL,
	escopo varchar(64) NOT NULL,
	condicao_json jsonb NULL,
	criado_por varchar(64) NOT NULL,
	criado_em timestamp NOT NULL,
	atualizado_por varchar(64) NULL,
	atualizado_em timestamp NULL
);
CREATE INDEX idx_permissao_org_usuario_1 ON seguranca.excecao_permissao_usuario USING btree (organizacao_id, usuario_id);


-- seguranca.log_auditoria definition

-- Drop table

-- DROP TABLE seguranca.log_auditoria;

CREATE TABLE seguranca.log_auditoria (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizacao_id uuid NULL,
	acao varchar(128) NOT NULL,
	tipo_entidade varchar(64) NULL,
	entidade_id uuid NULL,
	decisao varchar(16) NULL,
	metadados jsonb NULL,
	criado_por varchar(64) NOT NULL,
	criado_em timestamp NOT NULL
);
CREATE INDEX idx_auditoria_org_tempo_1 ON seguranca.log_auditoria USING btree (organizacao_id, criado_em);


-- seguranca.perfil_biometrico definition

-- Drop table

-- DROP TABLE seguranca.perfil_biometrico;

CREATE TABLE seguranca.perfil_biometrico (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	usuario_id varchar(64) NOT NULL,
	modelo_biometrico bytea NOT NULL,
	versao_modelo varchar(32) NOT NULL,
	criado_por varchar(64) NOT NULL,
	criado_em timestamp NOT NULL,
	atualizado_por varchar(64) NULL,
	atualizado_em timestamp NULL
);


-- seguranca.relacionamento definition

-- Drop table

-- DROP TABLE seguranca.relacionamento;

CREATE TABLE seguranca.relacionamento (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizacao_id uuid NOT NULL,
	sujeito_id varchar(64) NOT NULL,
	objeto_id varchar(64) NOT NULL,
	tipo_relacionamento varchar(64) NOT NULL,
	inicio_validade timestamp NULL,
	fim_validade timestamp NULL,
	criado_por varchar(64) NOT NULL,
	criado_em timestamp NOT NULL,
	atualizado_por varchar(64) NULL,
	atualizado_em timestamp NULL
);
CREATE INDEX idx_relacionamento_org_objeto_1 ON seguranca.relacionamento USING btree (organizacao_id, objeto_id);
CREATE INDEX idx_relacionamento_org_sujeito_1 ON seguranca.relacionamento USING btree (organizacao_id, sujeito_id);


-- seguranca.identidade_acesso definition

-- Drop table

-- DROP TABLE seguranca.identidade_acesso;

CREATE TABLE seguranca.identidade_acesso (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id int8 NOT NULL,
    keycloak_sub varchar(64) NOT NULL,
    provedor varchar(32) DEFAULT 'keycloak' NOT NULL,
    criado_em timestamp DEFAULT now() NOT NULL,
    CONSTRAINT fk_identidade_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa.pessoa(id) ON DELETE CASCADE,
    CONSTRAINT uq_identidade_sub UNIQUE (keycloak_sub)
);

-- Índice para otimizar as buscas no momento do login pelo interceptador de segurança
CREATE INDEX idx_identidade_acesso_sub ON seguranca.identidade_acesso USING btree (keycloak_sub);

